---
language: 'perl'
perl:
  - "5.26" # Ubuntu 18
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
install:
  - cpanm File::Find::Rule~0.34
  - cpanm Geo::Address::Formatter~1.76
script:
  - bin/run_tests.t
